name: deploy-main

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy ICACCPA
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/icaccpa.in/public_html

            git fetch origin master
            git reset --hard origin/master
