name: deploy-main

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy ICACCPA
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/html/icaccpa.in/public_html
            git pull
